Repository CPNV-ES/maw11-jdn, pull requests merged in 2024-12, with the labels that each got.

#42 feature/response-exercise
  app/controllers/ExerciseController.php
  app/models/FulfillmentModel.php
  app/views/home/response-exercise.php
  app/views/home/result-exercise.php
  app/views/home/result-field.php
  app/views/layouts/header.php
  public/css/result-field.css
  public/css/result-pages.css
Labels: feature, pending review

#43 Feature/fulfill exercises
  app/controllers/ExerciseController.php
  app/models/AnswerModel.php
  app/models/FulfillmentModel.php
  app/views/home/fulfill-exercise.php
  db/create_database.sql
Labels: feature, pending review

#47 Feature/all fulfill
  app/controllers/ExerciseController.php
  app/models/FulfillmentModel.php
  app/views/home/all-fulfill.php
  public/css/all-fulfill.css
Labels: feature

#52 Feature/refactor database
  README.md
  app/core/Database.php
  app/core/Model.php
  config/config.example.php
  database/maw11_jdn.sql
  db/create_database.sql
  db/database.example.sqlite
  db/insert_fake_data.sql
  docs/repo-structuring.md
  logs/.gitkeep
  public/index.php
  run
  tests/DatabaseTest.php
  tests/database/maw11_jdn_test.sql
  tests/db/create_database_test.sql
  tests/db/database_test.sqlite
  tests/db/insert_fake_data_test.sql
Labels: pending review
