Repository CPNV-ES/maw11-jdn, pull requests merged in 2024-11, with the labels that each got.

#23 Feature/exercises-icons-event
  .gitignore
  app/controllers/ExerciseController.php
  app/models/FieldModel.php
  app/views/home/field-exercise.php
  app/views/home/manage-exercise.php
  app/views/home/result-exercise.php
Labels: feature, pending review

#24 Feature/take exercise method
  app/controllers/ExerciseController.php
  app/views/home/manage-exercise.php
  app/views/home/result-exercise.php
  app/views/home/take-exercise.php
Labels: feature, pending review

#28 Bugfix/delete non existent exercise
  app/controllers/ExerciseController.php
Labels: bug, pending review

#27 fix: fix link when editing fullfil
  app/controllers/ExerciseController.php
  app/views/home/fulfill-exercise.php
Labels: bug, pending review

#35 Feature/create field exercise
  app/controllers/ExerciseController.php
  app/models/FieldModel.php
  app/views/home/create-field.php
  public/css/create-field.css
Labels: feature, pending review

#39 Version 1.2.0
  app/controllers/ExerciseController.php
  app/models/FieldModel.php
  app/views/home/create-exercise.php
  app/views/home/create-field.php
  app/views/home/fulfill-exercise.php
  app/views/home/home.php
  app/views/home/manage-exercise.php
  app/views/home/result-exercise.php
  app/views/home/take-exercise.php
  app/views/layouts/app-layout.php
  app/views/layouts/header.php
  public/css/create-field.css
  public/css/manage-exercise.css
  public/css/result-exercise.css
  public/index.php
Labels: pending review

#36 Feature/field result exercises
  app/controllers/ExerciseController.php
  app/models/AnswerModel.php
  app/models/FieldModel.php
  app/models/FulfillmentModel.php
  app/views/home/result-exercise.php
  app/views/layouts/header.php
  db/create_database.sql
  db/insert_fake_data.sql
Labels: feature, pending review

#41 Feature/field results
  app/controllers/ExerciseController.php
  app/models/FieldModel.php
  app/views/home/result-field.php
  public/css/result-exercise.css
  public/css/result-field.css
Labels: feature, pending review
