Repository CPNV-ES/maw11-jdn, pull requests merged in 2024-09, with the labels that each got.

#9 Feature/readme update
  .gitignore
  README.md
  composer.json
  composer.lock
Labels: documentation, feature, pending review

#10 Feature/review sprint1
  .gitignore
  README.md
  app/core/Router.php
  db/database.sqlite
  public/index.php
Labels: documentation, feature

#12 Feature/home page view
  app/controllers/HomeController.php
  app/core/Controller.php
  app/views/home/home.php
  db/database_name.sqlite
  public/css/home-style.css
  public/css/style.css
  public/images/logo.png
  public/index.php
Labels: feature, pending review

#11 Feature/manage exercise page view
  app/controllers/ExerciseController.php
  app/views/home/.gitkeep
  app/views/home/manage-exercise.php
  db/database.sqlite
  public/css/manage-exercice.css
  public/css/style.css
  public/images/.gitkeep
  public/images/looper-logo.png
  public/index.php
Labels: feature, pending review

#14 Bugfix/redirection link
  app/controllers/.gitkeep
  app/controllers/ExerciseController.php
  app/views/home/home.php
  app/views/home/manage-exercise.php
  public/css/home-page.css
  public/css/style.css
  public/index.php
Labels: feature, pending review

#13 Feature/exercise creation view
  app/controllers/ExerciseController.php
  app/views/home/create-exercise.php
  app/views/home/manage-exercise.php
  public/css/create-exercise.css
  public/css/home-page.css
  public/css/manage-exercice.css
  public/css/style.css
  public/images/logoLooper.png
  public/index.php
Labels: feature, pending review
